sudo: required
services:
  - docker

before_install:
  - docker build -t red-tetris/backend -f server/Dockerfile.dev server/
  - docker build -t red-tetris/frontend -f server/Dockerfile.dev client/

script:
  - docker run red-tetris/backend npm run coverage
  - docker run red-tetris/frontend npm run coverage