FROM node:8.15.1-alpine as builder
WORKDIR /app
COPY package.json ./
RUN npm install && npm run tsc && npm prune --production
COPY . .
EXPOSE 4000
CMD ["npm", "run", "prod"]

FROM node:8.15.1-alpine
ENV NODE_ENV=production
ENV PORT=4000
WORKDIR /app
RUN mkdir dist && mkdir node_modules
COPY --from=builder /app/dist ./dist
COPY --from=builder /app/node_modules ./node_modules
EXPOSE 4000
CMD ["node", "dist/index.js"]